databases:
  - name: playermetrixdb
    plan: starter
    databaseName: playermetrix
    user: statsuser

services:
  - type: web
    plan: basic-256mb
    name: playermetrix
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn playermetrix.asgi:application -k uvicorn.workers.UvicornWorker --max-requests 1000 --max-requests-jitter 100'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playermetrixdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2