databases:
  - name: playermetrixdb
    plan: free
    databaseName: playermetrix
    user: statsuser

services:
  - type: web
    plan: free
    name: playermetrix
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn playermetrix.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playermetrixdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4