# Generated by Django 4.1.4 on 2023-11-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('members', '0002_remove_profile_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='players.players'),
            preserve_default=False,
        ),
    ]
