# Generated by Django 4.1.4 on 2023-12-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_location_profile_city_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
