# Generated by Django 5.2.5 on 2026-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_playermetric_capturedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
