# Generated by Django 5.2.5 on 2026-05-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playerprofile_firstname_playerprofile_lastname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='profile_name',
            field=models.CharField(blank=True, help_text='Label this profile, e.g. "John - 2025 Season"', max_length=100, null=True, verbose_name='Profile Name'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
