# Generated by Django 5.2.5 on 2026-05-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_playerprofile_profile_name_alter_playerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='profile_name',
        ),
    ]
