# Generated by Django 5.2.5 on 2026-05-11 23:44

import re
from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    PlayerProfile = apps.get_model('main', 'PlayerProfile')
    used = set()
    for profile in PlayerProfile.objects.order_by('pk'):
        parts = [re.sub(r'[^\w]', '', p.lower()) for p in [profile.firstName, profile.lastName] if p]
        base = '_'.join(parts) or 'player'
        slug, counter = base, 2
        while slug in used:
            slug = f'{base}_{counter}'
            counter += 1
        profile.slug = slug
        profile.save(update_fields=['slug'])
        used.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_playerprofile_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
