# Generated by Django 5.2.5 on 2026-05-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_slug_to_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermetric',
            name='user',
        ),
        migrations.AddField(
            model_name='playermetric',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='main.playerprofile', verbose_name='Player Profile'),
        ),
    ]
