# Generated by Django 5.2.5 on 2026-05-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_playermetric_metrictype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='height_inches',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='weight_lbs',
        ),
    ]
