# Generated by Django 5.2.5 on 2026-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_playerprofile_height_inches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermetric',
            name='metricType',
            field=models.CharField(choices=[('60', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)'), ('catchvelo', 'Catcher Velocity (mph)'), ('poptime', 'Pop Time (seconds)'), ('changeup', 'Changeup (mph)'), ('curve', 'Curveball (mph)'), ('slider', 'Slider (mph)'), ('height', 'Height (inches)'), ('weight', 'Weight (lbs)')], max_length=20, verbose_name='Metric Type'),
        ),
    ]
