# Generated by Django 5.2.5 on 2026-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_playermetric_metrictype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsrange',
            name='metricType',
            field=models.CharField(choices=[('sixtyyard', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)')], max_length=20, verbose_name='Metric Type'),
        ),
        migrations.AlterField(
            model_name='playermetric',
            name='metricType',
            field=models.CharField(choices=[('sixtyyard', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)'), ('catchvelo', 'Catcher Velocity (mph)'), ('poptime', 'Pop Time (seconds)'), ('changeup', 'Changeup (mph)'), ('curve', 'Curveball (mph)'), ('slider', 'Slider (mph)'), ('height', 'Height (inches)'), ('weight', 'Weight (lbs)')], max_length=20, verbose_name='Metric Type'),
        ),
    ]
