# Generated by Django 5.2.5 on 2026-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_playerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='picture',
            field=models.ImageField(blank=True, default='player_pics/default.jpg', null=True, upload_to='player_pics/'),
        ),
    ]
