# Generated by Django 5.2.5 on 2026-07-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetric',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='main.event', verbose_name='Event'),
        ),
    ]
