# Generated by Django 5.2.5 on 2026-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='x_profile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='X (Twitter) Handle'),
        ),
    ]
