# Generated by Django 4.0.5 on 2023-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('highSchool', models.CharField(max_length=255)),
                ('gradYear', models.IntegerField()),
                ('throws', models.CharField(max_length=5)),
                ('hits', models.CharField(max_length=5)),
            ],
        ),
    ]
