# Generated by Django 4.1.4 on 2023-08-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True, default=None)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('eventDetails', models.TextField(blank=True, default=None)),
                ('link', models.CharField(blank=True, default=None, max_length=100)),
                ('registration', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
                ('ifVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('ofVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('cVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('popTime', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('exitVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('sixtyyard', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('maxFB', models.IntegerField(blank=True, default=None, null=True)),
                ('changeUp', models.IntegerField(blank=True, default=None, null=True)),
                ('curve', models.IntegerField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.events')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
