# Generated by Django 4.1.4 on 2023-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='firstName',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='players',
            name='gradYear',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='players',
            name='highSchool',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='players',
            name='hits',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='players',
            name='lastName',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='players',
            name='slug',
            field=models.SlugField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='players',
            name='throws',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
    ]
