# Generated by Django 4.1.4 on 2023-01-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('playerID', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
