# Generated by Django 4.1.4 on 2023-01-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='details',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.events'),
        ),
        migrations.AlterField(
            model_name='details',
            name='playerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
    ]
