# Generated by Django 4.1.4 on 2023-01-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_details_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='playerID',
            new_name='player',
        ),
    ]
