# Generated by Django 4.1.4 on 2023-11-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_players_gpa_players_instagramuser_players_positions_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='players',
            name='playerPositions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
