# Generated by Django 4.1.4 on 2023-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_eventid_details_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
