# Generated by Django 4.1.4 on 2023-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_players_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='cVelo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='changeUp',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='curve',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='exitVelo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='ifVelo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='maxFB',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='ofVelo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='popTime',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='details',
            name='sixtyyard',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='details',
            name='height',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='details',
            name='weight',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
