# Generated by Django 4.1.4 on 2023-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_players_playerpositions_players_catcher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='playerPositions',
        ),
        migrations.AlterField(
            model_name='players',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, max_length=255),
        ),
    ]
