# Generated by Django 4.1.4 on 2023-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_events_eventdetails_events_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventDetails',
            field=models.TextField(blank=True, default=None),
        ),
    ]
