# Generated by Django 4.1.4 on 2023-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_events_eventdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registration',
            field=models.BooleanField(default=True),
        ),
    ]
