# Generated by Django 4.1.4 on 2023-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_remove_players_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
