# Generated by Django 4.1.4 on 2023-12-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_players_city_players_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
