# Generated by Django 4.1.4 on 2023-01-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_events_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cVelo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
