# Generated by Django 4.1.4 on 2023-02-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_details_changeup_alter_details_curve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
