# Generated by Django 4.1.4 on 2023-04-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLog',
        ),
    ]
