# Generated by Django 4.1.4 on 2023-08-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_blog_events_alter_players_options_players_image_and_more'),
        ('players', '0017_blog_slug'),
    ]

    operations = [
    ]
