# Generated by Django 4.1.4 on 2023-11-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='player',
        ),
    ]
