# Generated by Django 4.1.4 on 2023-12-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True, default=None)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('eventDetails', models.TextField(blank=True, default=None)),
                ('link', models.CharField(blank=True, default=None, max_length=100)),
                ('registration', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default=None, max_length=255)),
                ('lastName', models.CharField(blank=True, default=None, max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('highSchool', models.CharField(blank=True, default=None, max_length=255)),
                ('gradYear', models.IntegerField(blank=True, default=None)),
                ('throws', models.CharField(blank=True, default=None, max_length=5)),
                ('hits', models.CharField(blank=True, default=None, max_length=5)),
                ('image', models.BooleanField(default=0)),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('instagramUser', models.CharField(blank=True, default=None, max_length=255)),
                ('xUser', models.CharField(blank=True, default=None, max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
                ('pitcher', models.BooleanField(default=False)),
                ('catcher', models.BooleanField(default=False)),
                ('firstbase', models.BooleanField(default=False)),
                ('secondbase', models.BooleanField(default=False)),
                ('thirdbase', models.BooleanField(default=False)),
                ('shortstop', models.BooleanField(default=False)),
                ('leftfield', models.BooleanField(default=False)),
                ('centerfield', models.BooleanField(default=False)),
                ('rightfield', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
                ('ifVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('ofVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('cVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('popTime', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('exitVelo', models.IntegerField(blank=True, default=None, null=True)),
                ('sixtyyard', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('maxFB', models.IntegerField(blank=True, default=None, null=True)),
                ('changeUp', models.IntegerField(blank=True, default=None, null=True)),
                ('curve', models.IntegerField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.events')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
