# Generated by Django 4.1.4 on 2024-06-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="showMetrics",
            field=models.BooleanField(default=False),
        ),
    ]
