# Generated by Django 4.1.4 on 2024-07-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_events_showmetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="slider",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="outfield",
            field=models.BooleanField(default=False),
        ),
    ]
