# Generated by Django 4.1.4 on 2023-11-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_picture_alter_players_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='gpa',
            field=models.FloatField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='players',
            name='instagramUser',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='players',
            name='positions',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='players',
            name='xUser',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
