# Generated by Django 4.1.4 on 2023-11-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_players_positions_players_playerpositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='positions',
        ),
    ]
