# Generated by Django 4.1.4 on 2023-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_players_positions'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='players',
            name='catcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='centerfield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='firstbase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='leftfield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='pitcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='rightfield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='secondbase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='shortstop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='thirdbase',
            field=models.BooleanField(default=False),
        ),
    ]
