# Generated by Django 4.1.4 on 2023-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_details_cvelo_details_changeup_details_curve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventDetails',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
