# Generated by Django 4.1.4 on 2023-11-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_players_playerpositions_alter_players_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='gpa',
        ),
    ]
