# Generated by Django 4.1.4 on 2023-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
